### ISSUE TITLE
Build a browser version of jettison.js

### ISSUE THREAD

**Issue by noonat** [noonat/jettison#7]
The compiled version of jettison.js only works from within node or browserify type setups right now. There should be a version uploaded somewhere as part of a release that can be used standalone on the client side.

**Comment by noonat** [comment]
I had made some progress on this, but had to remove the WIP in 922a8e0715d12898c84c3055054c9f3342d3089b, because it was causing some issues in downstream users of browserify. For example:

```
nathano@combine spacerocks $ npm start

> spacerocks@0.1.0 start /Users/nathano/Source/noonat/spacerocks
> babel-node src/server.js

Listening on port 8080
Error: Cannot find module 'coffeeify' from '/Users/nathano/Source/noonat/spacerocks/node_modules/jettison'
    at /Users/nathano/Source/noonat/spacerocks/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:46:17
    at process (/Users/nathano/Source/noonat/spacerocks/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/nathano/Source/noonat/spacerocks/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/nathano/Source/noonat/spacerocks/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/nathano/Source/noonat/spacerocks/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:92:31)
    at /Users/nathano/Source/noonat/spacerocks/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by noonat** [comment]
No longer using coffeescript, so might be able to resurrect the old code.
